@startuml
  hide footbox

  actor ": Użytkownik" as u
  participant ": FormularzDaneOsobowe" as fd
  participant ": FormularzDanePłatnicze" as fp
  participant ": Serwer" as s
  database ": BazaDanych" as db

  '1 - Użytkownik wypełnia formularz o danych osobowych
  u ->> fd ** : <<create>>\n1: utworzFormDane()

  u -> fd : 2: wprowadzDaneO()
  activate fd
  fd -->> u
  deactivate fd

  u -> fd : 3: zatwierdz()
  activate fd
  fd -> s : 4: wyslijDaneO()
  deactivate fd
  activate s
  s ->> u
  deactivate s

  '2 - (opt) Użytkownik wypełnia dane płatnicze
  opt
    u ->> fp ** : <<create>>\n5: utworzFormPlatn()
    u -> fp : 6: wprowadzDaneP()
    activate fp
    fp -->> u
    deactivate fp

    u -> fp : 7: zatwierdz()
    activate fp
    fp -->> s : 8: wyslijDaneP()
    deactivate fp
    activate s
    s --> u
    deactivate s
  end

  '3 - Potwierdzenie utworzenia konta
  u -> s : 9. zakoczWypelnianieDanych()
  activate s
  s -->> db : 10. zapiszDane()
  deactivate s
  activate db
  db -->> u
  deactivate db

  u ->> fp !! : <<destroy>>\n11: usunFP()
  u ->> fd !! : <<destroy>>\n12: usunFD()

@enduml