@startuml diagram-czynnosci-wynajecia-dzialki
title Diagram czynności - Wynajęcie działki

|Lista działek|
repeat
    repeat
        :Wybór działki przez Użytkownika;

        |Strona działki|
        :Strona ze szczegółowymi informacjami o działce;

    repeat while () is (rezygnacja) not (else)

    repeat

        :Wypełnienie informacji kontaktowych przez Użytkownika;
    repeat while (dane są poprawne) is (nie) not (tak)

    |Usługa płatnicza|
    :Użytkownik podaje dane płatnicze;
repeat while () is (Nie potwierdzono płatności) not (Potwierdzono płatność)

|Strona działki|
:Komunikat potwierdzający wynajęcie działki;
end

@enduml
